Feature: Name Sorting Core

  Background:
    Given the application is ready for file operations
    And the service package is "com.example.dd.nameSorter.service"
    And the testing templates directory is "src/test/resources/files"
    And the output files directory is "files"

  Scenario Outline: Validate Sorting Logic and Error Handling Across Implementations
    Given the following services are implemented:
      | serviceName                  | serviceAlias |
      | BinaryTreeNameSortingService | binaryTree   |
      | CollectionNameSortingService | collection   |
    And the input file "input-<caseId>.txt" and expected output file "output-<caseId>-expected.txt" are prepared
    When the sorting logic is executed for all services
    Then the output files "output-<caseId>-<serviceAlias>.txt" should be created with content matching "output-<caseId>-expected.txt"

    Examples: Test Cases
      | caseId | Summary                                               |
      | 1      | Empty lines in the file (Skip)                        |
      | 2      | Too many given names (Skip line and Write Warn Logs)  |
      | 3      | Missing Given names (Skip line and Write Warn logs)   |
      | 4      | Duplicated entries are preserved                      |
      | 5      | Sorting order is case insensitive                     |
      | 6      | Volume Test > 1000 records generated by AI            |